#!/usr/bin/env bash
#
# Obfuscate by @Clayshacker
# Contacta https://t.me/Clayshacker
# Channel: https://www.youtube.com/channel/UCDmwCTzunUqrQx6BxCAPkQQ
# NINGUN SISTEMA ES SEGURO 
#
CesarHackGray=$(mktemp)
base64 -d  >${CesarHackGray}<<DIXIE
cGtnIGluc3RhbGwgYXV0b2NvbmYgLXkKcGtnIGluc3RhbGwgYmlzb24gLXkKcGtnIGluc3RhbGwg
Y2xhbmcgLXkKcGtnIGluc3RhbGwgY29yZXV0aWxzIC15CnBrZyBpbnN0YWxsIGN1cmwgLXkKcGtn
IGluc3RhbGwgZmluZHV0aWxzIC15CnBrZyBpbnN0YWxsIGdpdCAteQpwa2cgaW5zdGFsbCBhcHIg
LXkKcGtnIGluc3RhbGwgYXByLXV0aWwgLXkKcGtnIGluc3RhbGwgbGliZmZpIC15CnBrZyBpbnN0
YWxsIGxpYmdtcCAteQpwa2cgaW5zdGFsbCBsaWJwY2FwIC15CnBrZyBpbnN0YWxsIHBvc3RncmVz
cWwgLXkKcGtnIGluc3RhbGwgcmVhZGxpbmUgLXkKcGtnIGluc3RhbGwgbGlic3FsaXRlIC15CnBr
ZyBpbnN0YWxsIG9wZW5zc2wgLXkKcGtnIGluc3RhbGwgbGlidG9vbCAteQpwa2cgaW5zdGFsbCBs
aWJ4bWwyIC15CnBrZyBpbnN0YWxsIGxpYnhzbHQgLXkKcGtnIGluc3RhbGwgbmN1cnNlcyAteQpw
a2cgaW5zdGFsbCBwa2ctY29uZmlnIC15CnBrZyBpbnN0YWxsIHdnZXQgLXkKcGtnIGluc3RhbGwg
cnVieSAteQpwa2cgaW5zdGFsbCBsaWJncnBjIC15CnBrZyBpbnN0YWxsIHRlcm11eC10b29scyAt
eQpwa2cgaW5zdGFsbCBuY3Vyc2VzIC15CnBrZyBpbnN0YWxsIG5jdXJzZXMtdXRpbCAteQpwa2cg
aW5zdGFsbCBsaWJzb2RpdW0gLXkKcGtnIGluc3RhbGwgdGVybXV4LWV4ZWMgLXkKcGtnIGluc3Rh
bGwgZ2l0IC15CnBrZyBpbnN0YWxsIHB5dGhvbiAteQpwa2cgaW5zdGFsbCBweXRob24yIC15CnBr
ZyBpbnN0YWxsIG9wZW5zc2ggLXkKcGtnIGluc3RhbGwgcGhwIC15CnBrZyBpbnN0YWxsIG5hbm8g
LXkKcGtnIGluc3RhbGwgdmltIC15CnBrZyBpbnN0YWxsIG1jIC15CnBrZyBpbnN0YWxsIGZpZ2xl
dCAteQpnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL3JhcGlkNy9tZXRhc3Bsb2l0LWZyYW1l
d29yawpjZCBtZXRhc3Bsb2l0LWZyYW1ld29yayAKZ2VtIGluc3RhbGwgYnVuZGxlcgpnZW0gaW5z
dGFsbCBidW5kbGUgCmJ1bmRsZSB1cGRhdGUgCmJ1bmRsZSB1cGRhdGUgbm9rb2dpcmkKZ2VtIGlu
c3RhbGwgbm9rb2dpcmkgLS0gLS11c2Utc3lzdGVtLWxpYnJhcmllcwpidW5kbGUgaW5zdGFsbCAt
ajUgCmNkICRIT01FL21ldGFzcGxvaXQtZnJhbWV3b3JrL2NvbmZpZwpjdXJsIC1MTyBodHRwczov
L0F1eGlsdXMuZ2l0aHViLmlvL2RhdGFiYXNlLnltbApta2RpciAtcCAkUFJFRklYL3Zhci9saWIv
cG9zdGdyZXNxbAp3Z2V0IGh0dHBzOi8vZ2l0aHViLmNvbS90ZXJtdXgvdGVybXV4LXBhY2thZ2Vz
L2ZpbGVzLzI5MTIwMDIvZml4LXJ1YnktYmlnZGVjaW1hbC5zaC50eHQKYmFzaCBmaXgtcnVieS1i
aWdkZWNpbWFsLnNoLnR4dApwa2cgaW5zdGFsbCB1bnN0YWJsZS1yZXBvIC15CnBrZyBpbnN0YWxs
IG1ldGFzcGxvaXQgLXkKCmNsZWFyCgpmaWdsZXQgQ0xBWVMgIAoK
DIXIE
source ${CesarHackGray}
rm -rf ${CesarHackGray}
